### ISSUE TITLE
Dask labextension does not work in latest images

### ISSUE THREAD

**Issue by rabernat** [pangeo-gallery/default-binder#21]
Pasting the dashboard link into the Dask labextension dialog has no effect. It does not recognize the link, and none of the buttons become active. I have tried this on several recent

![image](https://user-images.githubusercontent.com/1197350/103908821-f17f3f00-50d0-11eb-9243-d804f5cda489.png)

For example, here is a link for our classic example notebook using the latest commit of this repo (64d772a), which points to the latest pangeo-notebook docker image ([c8c0d72](https://hub.docker.com/layers/pangeo/pangeo-notebook/c8c0d72/images/sha256-009bced1742830aacb52602b954922d1e51d53dc814b529ab9030eec82426bb9?context=repo)).

https://binder.pangeo.io/v2/gh/pangeo-gallery/default-binder/64d772a/?urlpath=git-pull?repo=https://github.com/pangeo-gallery/physical-oceanography%26amp%3Burlpath=lab/tree/physical-oceanography/01_sea-surface-height.ipynb%3Fautodecode

What extra config are we missing to make the labextension work? It DOES work in https://us-central1-b.gcp.pangeo.io/, so something must be missing here. Something also must have changed since earlier versions, but I can't pinpoint the precise commit where things broke.

cc @scottyhq @TomAugspurger for any suggestions!

**Comment by jbusecke** [comment]
I am having the same issue. It especially impacts the way I can give interactive demos during presentations (leading to error-prone and distracting switching between windows). 

Is there any way we can fix this? Happy to help out in any way I can.

**Comment by TomAugspurger** [comment]
First thing to check would be the javascript console in your browser (typically under “Developer tools”). Are there any errors there?

**Comment by rabernat** [comment]
No, didn't get any errors in my JavaScript console.

**Comment by rabernat** [comment]
I think we should closely examine the difference between the gcp deployment and the binders to figure this out.

**Comment by rabernat** [comment]
> I think we should closely examine the difference between the gcp deployment and the binders to figure this out.

The only difference is the version of the image:
https://github.com/pangeo-gallery/default-binder/blob/64d772acdb0c35f5800f2733cfad3cf5447dec8f/binder/Dockerfile#L1

vs 

https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/gcp-uscentral1b/image/binder/Dockerfile#L1

**Comment by rabernat** [comment]
I'm going to close this in favor of https://github.com/pangeo-data/pangeo-docker-images/issues/177, since I think it is ultimately about package versions.
